# frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

COPY --chown=node:node package*.json ./
COPY --chown=node:node frontend/package*.json ./frontend/

RUN npm install

COPY --chown=node:node frontend/ ./frontend/

WORKDIR /app/frontend

USER node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]