# backend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

COPY --chown=node:node package*.json ./
COPY --chown=node:node backend/package*.json ./backend/

RUN npm install

COPY --chown=node:node backend/ ./backend/

WORKDIR /app/backend

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]